package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"
)

// Fixed certificate filenames — generated by: just gen-cert
const (
	certFile = "server.pem"
	keyFile  = "server-key.pem"
)

// ScanPayload represents the expected JSON structure from the HTML scanner
type ScanPayload struct {
	Barcode string `json:"barcode"`
}

// serveHtmlInterface serves the static HTML scanner file to the mobile browser
func serveHtmlInterface(w http.ResponseWriter, r *http.Request) {
	http.ServeFile(w, r, "index.html")
}

// handleScanEndpoint receives the POST request with the barcode data and validates it
func handleScanEndpoint(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var payload ScanPayload
	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		http.Error(w, "Invalid JSON payload", http.StatusBadRequest)
		return
	}

	// Clean up the barcode string just in case there are accidental whitespaces
	cleanBarcode := strings.TrimSpace(payload.Barcode)

	// Validate barcode length (12 digit UPC + 5 digit addon = 17 digits)
	if len(cleanBarcode) < 17 {
		fmt.Printf("[Scanner] Warning: Barcode too short (%s). Waiting for full 17 digits.\n", cleanBarcode)
		// Return HTTP 400 with a specific error message for the frontend
		http.Error(w, "Barcode missing the 5-digit extension.", http.StatusBadRequest)
		return
	}

	fmt.Printf("[Scanner] Success: Received complete barcode: %s\n", cleanBarcode)

	// TODO: Trigger API lookup (Metron) and database storage here
	// Example: metadata, err := ParseBarcode(cleanBarcode)

	w.WriteHeader(http.StatusOK)
}

func main() {
	mux := http.NewServeMux()

	mux.HandleFunc("/scanner", serveHtmlInterface)
	mux.HandleFunc("/style.css", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "style.css")
	})

	port := ":8080"
	fmt.Println("Starting Comic Scanner...")
	fmt.Printf("Open on your phone: https://<YOUR_LOCAL_IP>%s/scanner\n", port)
	fmt.Println("(Run 'just ca-path' to find the root CA file for mobile import)")

	log.Fatal(http.ListenAndServeTLS(port, certFile, keyFile, mux))
}
